server:
  port: 80
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: conta-service
  redis:
    host: 192.168.0.106
    port: 6379
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://192.168.0.106:3306/account?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

app:
  product: http://product

management:
  server:
    port: 4004
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true