version: "3.3"
services:

  mysql:
    image: mysql
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: "financeiro"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306

  zookeeper:
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - kafka-net 

  kafka:
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - "ES_HOSTS=elasticsearch:9300"
    ports:
      - "9411:9411"

networks:
  kafka-net:
    driver: bridge