fullnameOverride: product

image:
  name: product-finance-tax

env:
  SPRING_CONFIG_LOCATION: file:/config-repo/application.yml

livenessProbe_enabled: true

readinessProbe_enabled: true

configmap:
  enabled: true
  volumeMounts:
    mountPath: /config-repo
