account:
  url: http://conta

server:
  port: 80
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 20
spring:
  application:
    name: operation
  redis:
    host: 192.168.0.113
    port: 6379
  cloud:
    stream:
      bindings:
        product-out-0:
          group: '${spring.application.name}'
          content-type: application/json
          destination: operation-group
  kafka:
    bootstrap-servers: 192.168.0.113:9092


management:
  server:
    port: 4004
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true