server:
  port: 80
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 20

spring:
  sleuth.sampler.percentage: 1
  application:
    name: product-service
  redis:
    host: 192.168.0.113
    port: 6379
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://192.168.0.113:3307/financeiro?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  cloud:
    stream:
      bindings:
        operation-in-0:
          group: '${spring.application.name}'
          content-type: application/json
          destination: operation-group
  kafka:
    bootstrap-servers:
      - my-release-kafka:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false


management:
  server:
    port: 4004
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

cron:
  reset: "* * 23 * * ?"
