server:
  port: 8181
  shutdown: graceful
  tomcat:
    accept-count: 100
    connection-timeout: 2000
    max-connections: 8192
    threads:
      max: 200
      min-spare: 20

spring:
  application:
    name: product-service
  redis:
    host: localhost
    port: 6379
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 1000
    url: jdbc:mysql://localhost:3306/financeiro?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  cloud:
    stream:
      bindings:
        operation-in-0:
          group: '${spring.application.name}'
          content-type: application/json
          destination: operation-group
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false


management:

  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true